In [4]:
import math
import numpy as np

In [2]:
def gauss(sig, x, y):
    lower = 2*math.pi*sig*sig
    deg = (-x*x-y*y)/(2*sig*sig)
    return pow(math.e, deg)/lower


In [3]:
gauss(1,1,1)

0.05854983152431917

In [37]:
def gauss_kernel(sig):
    k = round(6*sig+1)
    kernel = np.ones((k,k))
    for i in range(len(kernel)):
        for j in range(len(kernel[0])):
            kernel[i][j] = gauss(sig, i-k//2, j-k//2)
    return  kernel/kernel.sum()
print(gauss_kernel(0.33))
k = gauss_kernel(0.33)
for i in range(len(k)):
    for j in range(len(k[0])):
        e = " " if j!=len(k)-1 else "\n"
        print(round(k[i][j], 4), end=e)

[[9.87532107e-05 9.73995858e-03 9.87532107e-05]
 [9.73995858e-03 9.60645153e-01 9.73995858e-03]
 [9.87532107e-05 9.73995858e-03 9.87532107e-05]]
0.0001 0.0097 0.0001
0.0097 0.9606 0.0097
0.0001 0.0097 0.0001


In [16]:
n = 3
arr = np.zeros((n,n))

# calculate the indices of the center of the array
center = n//2

# create a 2D Gaussian kernel centered at the middle of the array
sigma = 0.33
kernel = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        x = i - center
        y = j - center
        kernel[i,j] = np.exp(-(x**2 + y**2)/(2*sigma**2))
kernel /= kernel.sum()

kernel

array([[9.87532107e-05, 9.73995858e-03, 9.87532107e-05],
       [9.73995858e-03, 9.60645153e-01, 9.73995858e-03],
       [9.87532107e-05, 9.73995858e-03, 9.87532107e-05]])

In [8]:
arr = np.zeros((7,7))
arr[-3, 3] = 1
# access the top left corner relative to the center
top_left = arr[-3, 3]

print(top_left)

1.0


In [38]:
from skimage.io import imread, imshow
from skimage import img_as_float, img_as_ubyte
from scipy.signal import convolve2d
import numpy as np

In [52]:
img = imread('tiger-gray-small.png')
filter = gauss_kernel(0.66)
res_img = convolve2d(img, filter, mode="valid")
res_img = (res_img).astype(int)
res_img.max()

254

In [44]:
filter.size

25

In [53]:
tg = imread('gaussian-tiger.png')
np.array_equal(tg, res_img)

True

In [75]:
kernel = np.array([[-1, -2, -1], [-2, 22, -2], [-1, -2, -1]])
img = imread('tiger-gray-small.png')
res_img = convolve2d(img, kernel, mode="valid")/10
res_img = res_img.astype('uint8')
# res_img= np.clip(res_img, 0, 255).astype(int)
# np.array_equal(res_img, imread('unsharp-tiger.png'))

In [76]:
tg = imread('unsharp-tiger.png')
tg

array([[ 34,  37,  37, ...,   3,   0,   2],
       [ 35,  37,  38, ...,   5,   1,   2],
       [ 33,  42,  43, ...,   4,   2,   1],
       ...,
       [173, 188, 150, ..., 116, 123, 108],
       [152, 148, 129, ..., 108, 120, 103],
       [ 85,  74,  72, ..., 119, 111, 131]], dtype=uint8)

In [77]:
np.array_equal(tg, res_img)

False

In [80]:
img = imread('tiger-gray-small.png')
out_img = np.ones((img.shape[0], img.shape[1]))
for i in range(3,img.shape[0]-3):
    # проходим по столбцам
    for j in range(3,img.shape[1]-3):
        # вычленяем из изображения кусок 7х7
        a = img[i-3:i+4,j-3:j+4]
        # считаем его медиану
        m = np.median(a)
        # записываем в результат
        out_img[i][j]=m
# обрезаем результат
out_img = out_img[3:img.shape[0]-3,3:img.shape[1]-3]
# сохраняем
out_img

array([[ 41.,  41.,  41., ...,   4.,   4.,   3.],
       [ 41.,  41.,  41., ...,   4.,   4.,   4.],
       [ 41.,  41.,  41., ...,   6.,   5.,   5.],
       ...,
       [102., 103., 103., ..., 100., 103., 103.],
       [103., 103., 103., ..., 103., 106., 107.],
       [111., 109., 112., ..., 104., 108., 109.]])